---
title: ''
output: pdf_document
header-includes:
  - \setcounter{secnumdepth}{2}
  - \usepackage{float}
  - \usepackage{setspace}
  - \usepackage{ragged2e}
  - \usepackage{etoolbox}
---


\section{Introduction}

\vspace{0.5cm}


\begin{flushleft}
\begin{spacing}{2}

In most countries, including the United States, the gender pay gap has narrowed since the 1970s, though it remains a significant issue (Our World in Data, 2018). Between 1970 and 2018, the women-to-men ratio of hourly wages increased from 0.61 to 0.83 but has stagnated since the 1990s, with the largest disparities observed among the top 10\% of earners (England, Levine, \& Mishel, 2020). This is despite the fact that women have been increasingly outpacing men in college completion (England et al, 2020; Yavorsky et al., 2019). It may be the case that credential and labor market disparities across the life course—i.e., through college, in the transition from higher education to employment, and relative to labor market attachment over time—might be at least partly responsible. \par

Most research on the gender wage gap has concentrated on the gendered STEM pipeline as a key source of unequal earnings. Specifically, scholars have analyzed disparities in college majors, particularly the persistence and completion of STEM degrees, as well as resulting gender segregation in occupations and industries (Kim, Tamborini, and Sakamoto; 2015; Mann \& DiPrete, 2013; VanHeuvelen \& Quadlin, 2021). Fewer studies, however, have explored how educational choices made during emerging adulthood shape individuals' long-term labor market experiences and attachments in particular. This is somewhat surprising as labor market attachment has long been a focal point for economists and family scholars investigating women’s occupational downgrading (Becker, 1985). More recently, this focus has expanded to include the growing prevalence of time-demanding, disproportionately high-paying occupations and the systemic advantages men enjoy in these roles, including their capacity to overwork (Cha \& Weeden, 2014; Goldin, 2014).

\end{spacing}
\end{flushleft}

